"""empty message

Revision ID: c2ab89b2cffc
Revises: 
Create Date: 2019-11-10 20:53:58.157532

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c2ab89b2cffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['id'])
    op.drop_column('comments', 'user_avatar')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column(
        'comments',
        sa.Column('user_avatar', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
